### PR TITLE
Clarify opening pitch

### PR DESCRIPTION
**Pull request by chadwhitacre**
Intended to address #25.

# Before

Screenshot 2024-01-03 at 1 35 21 PM

# After

Screenshot 2024-01-03 at 1 35 37 PM

### CODE REVIEW

**Comment by chadwhitacre** [comment]
You good with this @colindean?

**Comment by colindean** [comment]
I think this helps clarify the table adequately _for me_ given the conversation that we had in #25, but I think a clearer paragraph would be more valuable than the table.

A Venn diagram might be more illustrative.

**Comment by chadwhitacre** [comment]
> A Venn diagram might be more illustrative.

Hrm, I thought this through a little bit, and afaict there are five sets to represent, three of which are non-overlapping. I think a Venn diagram would be [_more_ complicated](https://www.youtube.com/watch?v=YnTyt79Ajyk#t=41).

> I think a clearer paragraph would be more valuable than the table.

I think the paragraph on this PR is clear. It feels like you're hung up on whether there's a table or not, and aren't acknowledging the prose that already exists on the site as an alternate presentation of the same information, nor the improvements to that prose on this PR. Different people can find different presentations helpful. So far I think it's fine to have both a table and a paragraph, and that the improvements to both on this PR are sufficient to close #25.

Thanks for the feedback! :-)

**Comment by colindean** [comment]
Thanks. What's here is an improvement!

**Pull request merged**
