### PR TITLE
Add Frontend Masters

### PR DESCRIPTION
**Pull request by chadwhitacre**
Look good, @1Marc?

Do you have a version of logo that works better on a light background? This works but "Frontend" gets a little lost.

Screenshot 2023-11-06 at 9 34 34 AM

### CODE REVIEW

**Comment by 1Marc** [comment]
Yea, our "on white" logo is here: https://static.frontendmasters.com/assets/brand/logos/full.png

**Comment by 1Marc** [comment]
If you want the SVG version, I just swapped the "Frontend" color to #3e3e3e

frontendmasters_onwhite

**Comment by chadwhitacre** [comment]
Thanks, pushed!

**Comment by chadwhitacre** [comment]
Taking your comments as a +1. 🙂 

Merging!

Screenshot 2023-11-06 at 7 03 22 PM

**Pull request merged**
