### PR TITLE
Add Pydantic

### PR DESCRIPTION
**Pull request by chadwhitacre**
You up for this, @samuelcolvin? :)

Lmk if you would like a different logo file and/or link.

cc: @jdorfman

### CODE REVIEW

**Comment by jdorfman** [comment]
join the fam sam

**Comment by samuelcolvin** [comment]
:+1: LGTM.

**Comment by samuelcolvin** [comment]
https://github.com/orgs/pydantic/sponsoring might be a better link?

**Comment by chadwhitacre** [comment]
I made an SVG wordmark that matches the SVG logo + font in the header on https://pydantic.dev/. This makes it easier to work with a light vs. dark background. Hopefully that's okay?

Screenshot 2023-09-15 at 7 14 53 PM

**Comment by chadwhitacre** [comment]
> [sponsoring](https://github.com/orgs/pydantic/sponsoring) might be a better link?

Hrm ... so we're early days here with only four logos on the site, but I guess my take would be that we want to link to pages where each company can give more details about their FOSS funding program. If we simply link to Sponsors profiles, that doesn't add much value over what GitHub does already (or should be doing better, it needs a leaderboard or some such imo). What we're looking to encourage here is for each company to say in their own voice how they approach this topic.

1. I think the tweet/post is fine to start.
2. Even better would be a blog post about why this is important to Pydantic, how you are approaching the topic, why you picked Encode as well as the other four you are sponsoring right now, maybe plans for the future, etc.
3. Long-term I think we should steer towards each company having a more permanent page under their control where they describe their funding program (e.g. for Sentry this will likely go up on https://open.sentry.io/).

What do you think @samuelcolvin @jdorfman?

**Comment by samuelcolvin** [comment]
LGTM 👍.

**Comment by jdorfman** [comment]
@chadwhitacre :shipit:

**Comment by chadwhitacre** [comment]
Thanks @jdorfman, welcome aboard @samuelcolvin! :-)

I started a [README](https://github.com/fossfunders/fossfunders.com#readme) in #14 building on the comments above.

**Pull request merged**
