### PR TITLE
Add Spotify

### PR DESCRIPTION
**Pull request by chadwhitacre**
You good with this, ~@/pploug~? :)

### CODE REVIEW

**Comment by chadwhitacre** [comment]
@dzolotusky I guess this is you now? I tried guessing your work email address and failed. 😬 Hopefully this gets through ...

> Congrats on shipping Spotify's [2023 FOSS Fund](https://engineering.atspotify.com/2023/10/announcing-the-recipients-of-the-2023-spotify-foss-fund/)! I guess you took this over from Per? Are you aware of the [fossfunders.com](http://fossfunders.com/) website and biweekly call? You're welcome to join the call if you like (we just had one yesterday). May I [add Spotify's logo](https://github.com/fossfunders/fossfunders.com/pull/19) on the website with a link to your post?

**Comment by dzolotusky** [comment]
Yes, this is me now.
I was not aware of fossfunders.com until now, but this looks very cool.
I'll try to join the calls when I can.
I'm not sure how long it will take, but I'm going to go figure out how to get approval for the logo to appear here and will get back to you.

**Comment by chadwhitacre** [comment]
Yay! Welcome, @dzolotusky! 😁 I will leave this open for now, good luck getting approval! Maybe if/when you are successful it will encourage others ahem @awright. ;-)

@DuaneOBrien Can we add @dzolotusky to the call invite?

**Comment by DuaneOBrien** [comment]
Sure thing. @dzolotusky I'll need an email address. Ping me in the TODO Slack if you're there, or hit me up on gmail (it's just my first_name.last_name)

**Comment by dzolotusky** [comment]
I got approval to list us, but we'd like to use our new Spotify R&D logo.
RnD Logo-black

**Comment by chadwhitacre** [comment]
Woo-hoo! Awesome! Rebased in df3fa4aee615dac85a3f020a383bbf0c2ca61c6d and logo updated in 26245f82c79b69ce3dea1f462c01f7d89e6400a9. 💃 

Screenshot 2023-11-13 at 5 36 30 PM

**Comment by chadwhitacre** [comment]
We're live! [X post](https://twitter.com/fossfunders/status/1724196434692448269).

**Pull request merged**
