### PR TITLE
Add Foxley Talent

### PR DESCRIPTION
**Pull request by chadwhitacre**
@JonG0uld Congrats on [the ship](https://foxleytalent.com/blog/donating-to-the-django-software-foundation/)! Let's get you added to fossfunders.com. 👍

Can you provide a wordmark SVG or PNG for us here?

### CODE REVIEW

**Comment by chadwhitacre** [comment]
P.S. Consider redirecting https://foxleytalent.com/blog/donating/ to the updated URL since it's [out on X/Twitter](https://twitter.com/JonG0uld/status/1729541960900194498)?

**Comment by JonG0uld** [comment]
foxley logo2 0

**Comment by chadwhitacre** [comment]
Ooof ... could we get one with a transparent background? 🐭

**Comment by JonG0uld** [comment]
foxley logo2 0

does this one work?

**Comment by chadwhitacre** [comment]
I'm still seeing a white background on it.

Screenshot 2023-11-29 at 9 33 43 AM

**Comment by chadwhitacre** [comment]
Looking good! Thanks @JonG0uld!

Screenshot 2023-11-30 at 10 29 04 AM

**Pull request merged**
