### PR TITLE
Add Target

### PR DESCRIPTION
**Pull request by chadwhitacre**
You up for this, @bmuenzenmeyer? :-)

Screenshot 2024-03-11 at 6 18 31 PM

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Hey @chadwhitacre 

This is very cool to be recognized here so quickly after our announcement today. You are on the pulse! I need to talk to some folks before proceeding, so please sit tight.

**Comment by chadwhitacre** [comment]
Sounds good, keep us posted! 😁

**Comment by bmuenzenmeyer** [comment]
Btw, last status on this was with foss funders needing to review logo mark terms.

Happy to resend.

**Comment by chadwhitacre** [comment]
Thanks @bmuenzenmeyer. I'm stepping back from FOSS Funders leadership, will let @DuaneOBrien or others pick this up  when ready.

**Pull request closed without merging**
